branches:
  only:
  - master

environment:
  nodejs_version: '5.2.0'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off
version: '{build}'
shallow_clone: true
clone_depth: 1

test_script:
  - node --version
  - npm --version
  - set BABEL_DISABLE_CACHE=1
  - set NODE_ENV=TEST
  - node node_modules\mocha\bin\mocha ./test/runtime.spec.js
